ALTER TABLE `imagens` AUTO_INCREMENT=1;
ALTER TABLE `logs` AUTO_INCREMENT=1;
ALTER TABLE `portoes_pessoas` AUTO_INCREMENT=1;
ALTER TABLE `pessoas_has_veiculos` AUTO_INCREMENT=1;
ALTER TABLE `cameras` AUTO_INCREMENT=1;
ALTER TABLE `cookies` AUTO_INCREMENT=1;
ALTER TABLE `placas` AUTO_INCREMENT=1;
ALTER TABLE `empresas` AUTO_INCREMENT=1;
ALTER TABLE `operacoes` AUTO_INCREMENT=1;
ALTER TABLE `pessoas` AUTO_INCREMENT=1;
ALTER TABLE `veiculos` AUTO_INCREMENT=1;
ALTER TABLE `portoes` AUTO_INCREMENT=1;

